module.exports = {
    SUCCESS: 'success',
    RESOURCE_NOT_FOUND: "The resource has not been found on the server.",
    RESOURCE_SUCCESSFULLY_CREATED: "The resource has been successfully created.",
    RESOURCE_NOT_CREATED: "The creation of the resource has failed.",
    RESOURCES_SUCCESSFULLY_CREATED: "The resources has been successfully created.",
    RESOURCES_NOT_CREATED: "The creation of resources has failed.",
    RESOURCE_SUCCESSFULLY_FETCHED: "The resource has been successfully fetched.",
    RESOURCES_SUCCESSFULLY_FETCHED: "The resources have been successfully fetched.",
    RESOURCE_SUCCESSFULLY_UPDATED: "The resource has been successfully updated.",
    RESOURCE_NOT_UPDATED: "The resource has not been updated.",
    RESOURCE_SUCCESSFULLY_DELETED: "The resource has been successfully deleted.",
    RESOURCES_SUCCESSFULLY_DELETED: "The resources have been successfully deleted.",
    RESOURCES_NOT_SUCCESSFULLY_DELETED: "The resources haven't been successfully deleted.",
    INTERNAL_ERROR: "Internal error",
    CONNECTION_ESTABLISHED: 'Connection established',
    CONNECTION_CLOSED: 'Connection closed',
    CALL_HELP_TRIGGERED: 'Call for help triggered',
    CANCEL_CALL_TRIGGERED: 'Cancel call triggered',
}